[phases]
  [phases.install]
    nixPkgs = ['python312', 'pipx']
  [phases.build]
    cmds = [
      'python -c "import subprocess,sys,os; open(\'BUILD_SHA\',\'w\').write(os.getenv(\'RAILWAY_GIT_COMMIT_SHA\',\'\')[0:7] or \"unknown\")"'
    ]
[processes]
  web = "uvicorn webhook_app:app --host 0.0.0.0 --port $PORT"
