[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.virtualenv", "deno"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["deno cache supabase/functions/fastener-search/index.ts"]

[start]
cmd = "source venv/bin/activate && python bot.py"
