[phases.setup]
nixPkgs = ["python311"]

[phases.install]
commands = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
command = "uvicorn webhook_app:app --host 0.0.0.0 --port $PORT"
