name: Test FastenersAI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run basic tests
      run: |
        python -c "import sys; print('Python version:', sys.version)"
        python -c "import telegram; print('Telegram bot library installed')"
        python -c "import supabase; print('Supabase library installed')"
        python -c "import openai; print('OpenAI library installed')"
        
    - name: Check file structure
      run: |
        echo "Checking project structure..."
        ls -la
        echo "Checking handlers directory..."
        ls -la handlers/
        echo "Checking services directory..."
        ls -la services/
        
    - name: Validate configuration
      run: |
        echo "Checking configuration files..."
        if [ -f "config.py" ]; then
          echo "✅ config.py exists"
        else
          echo "❌ config.py not found"
        fi
        
        if [ -f "requirements.txt" ]; then
          echo "✅ requirements.txt exists"
          echo "Dependencies:"
          cat requirements.txt
        else
          echo "❌ requirements.txt not found"
        fi
